# Generated by Django 6.0.4 on 2026-04-12 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Positive = earned, negative = deducted.')),
                ('source', models.CharField(choices=[('task_correct', 'Correct Answer'), ('session_complete', 'Session Completed'), ('daily_streak', 'Daily Streak'), ('bonus', 'Manual Bonus'), ('deduction', 'Deduction')], max_length=30)),
                ('balance_after', models.PositiveIntegerField(help_text='Value of user.total_points after this transaction was applied.')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='learning_sessions.taskattempt')),
            ],
            options={
                'verbose_name': 'Point Transaction',
                'verbose_name_plural': 'Point Transactions',
                'ordering': ('-created_at',),
            },
        ),
    ]
