# Generated by Django 6.0.4 on 2026-04-12 19:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or CSS icon class', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('open_text', 'Open Text'), ('image_based', 'Image Based'), ('fill_blank', 'Fill in the Blank')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('question', models.TextField()),
                ('question_image', models.ImageField(blank=True, help_text='Required for image_based tasks.', null=True, upload_to='task_images/')),
                ('correct_answer', models.TextField(help_text='Stored server-side only. Must never appear in API responses.')),
                ('explanation', models.TextField(blank=True, help_text='Shown to student after the attempt.')),
                ('points_reward', models.PositiveSmallIntegerField(default=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveSmallIntegerField(help_text='School grade 1–11', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)])),
                ('title', models.CharField(max_length=200)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='content.subject')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ('grade', 'order'),
            },
        ),
        migrations.CreateModel(
            name='TaskChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. A, B, C, D', max_length=5)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='choice_images/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='content.task')),
            ],
            options={
                'verbose_name': 'Task Choice',
                'verbose_name_plural': 'Task Choices',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='content.book')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='content.topic'),
        ),
    ]
