# Generated by Django 6.0.4 on 2026-04-12 19:34

import apps.media_assets.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('video', 'Video'), ('game', 'Game'), ('audio', 'Audio'), ('image', 'Image'), ('document', 'Document')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.media_assets.models.asset_upload_path)),
                ('external_url', models.URLField(blank=True, help_text='YouTube link, hosted game URL, etc. Use instead of file when applicable.')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='content.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='content.topic')),
            ],
            options={
                'verbose_name': 'Media Asset',
                'verbose_name_plural': 'Media Assets',
                'ordering': ('-created_at',),
            },
        ),
    ]
