# Generated by Django 6.0.4 on 2026-04-12 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('ocr_text', 'OCR Text'), ('audio', 'Audio'), ('action', 'Action')], default='text', max_length=20)),
                ('text', models.TextField(blank=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='ai_chat/')),
                ('action_type', models.CharField(blank=True, max_length=50)),
                ('action_payload', models.JSONField(blank=True, help_text='Arbitrary JSON passed to the frontend to trigger a UI action.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Chat Message',
                'verbose_name_plural': 'AI Chat Messages',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AIChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='content.topic')),
            ],
            options={
                'verbose_name': 'AI Conversation',
                'verbose_name_plural': 'AI Conversations',
                'ordering': ('-updated_at',),
            },
        ),
    ]
