# Generated by Django 6.0.4 on 2026-04-13 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0002_initial'),
        ('learning_sessions', '0003_taskattempt_ai_help_used_taskattempt_attempt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatconversation',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversation', to='learning_sessions.studentsession'),
        ),
    ]
