# Generated by Django 6.0.4 on 2026-04-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='character_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='voice_tone',
            field=models.CharField(choices=[('neutral', 'Neutral'), ('warm', 'Warm'), ('energetic', 'Energetic')], default='neutral', max_length=15),
        ),
    ]
