# Generated by Django 6.0.4 on 2026-04-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sessions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattempt',
            name='ai_help_used',
            field=models.BooleanField(default=False, help_text='If true, points are multiplied by 0.8.'),
        ),
        migrations.AddField(
            model_name='taskattempt',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='Which attempt this is for the task within the session (1 = first try).'),
        ),
    ]
